<div class="feature-top clear"></div>
<div id="feature" class="clear">
	<div class="feature-main">
		<div class="container">
			<div class="slides">
				<div id="slide-1" class="slide">
					<img width="602" height="200" src="<?php bloginfo( 'template_url' ); ?>/images/slider/beach-602x200.jpg" class="feature-photo wp-post-image" /><h3><a href="#">A day at the beach today</a></h3><p>Singing sand, whistling sand or barking sand is sand that produces sounds of either high or low frequency	under pressure. The sound emission is usually triggered by wind passing over dunes	or by walking on the sand. The sound is generated by shear stress.<br /><a href="#" class="more-link">Read more</a></p>
				</div>
				<div id="slide-2" class="slide">
					<img width="602" height="200" src="<?php bloginfo( 'template_url' ); ?>/images/slider/girl_5-602x200.jpg" class="feature-photo wp-post-image" /><h3><a href="#">Enjoying the weather</a></h3><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.<br /><a href="#" class="more-link">Read more</a></p>
				</div>
				<div id="slide-3" class="slide">
					<img width="602" height="200" src="<?php bloginfo( 'template_url' ); ?>/images/slider/outback-602x200.jpg" class="feature-photo wp-post-image" /><h3><a href="#">Hiking in the outback</a></h3><p>The Outback is the remote arid areas of Australia, although the term colloquially can refer to any lands outside of the main urban areas. The term &#8220;the outback&#8221; is generally used to refer to locations that are comparatively more remote than those areas deemed &#8220;the bush&#8221;.<br /><a href="#" class="more-link">Read more</a></p>
				</div>
			</div>
		</div>
</div><!--end feature-main-->
	<div class="feature-sidebar">
		<h2><?php _e( 'Featured Articles', 'traction' ); ?></h2>
		<ul class="pagination">
			<li id="slide-nav-1">
				<a class="clear" href="#">
					<img width="30" height="30" src="<?php bloginfo( 'template_url' ); ?>/images/slider/beach-30x30.jpg" class="attachment-feature-small wp-post-image" alt="Beach" title="singing-sands-beach" /><strong>A day at the beach</strong>
					<span>A day at the beach</span>
				</a>
			</li>
			<li id="slide-nav-2">
				<a class="clear" href="#">
					<img width="30" height="30" src="<?php bloginfo( 'template_url' ); ?>/images/slider/girl_5-30x30.jpg" class="attachment-feature-small wp-post-image" alt="Girl" title="girl_5" /><strong>Enjoying the weather</strong>
					<span>Beautiful day outside</span>
				</a>
			</li>
			<li id="slide-nav-3">
				<a class="clear" href="#">
					<img width="30" height="30" src="<?php bloginfo( 'template_url' ); ?>/images/slider/outback-30x30.jpg" class="attachment-feature-small wp-post-image" alt="Outback" title="1233309_15484861" /><strong>Hiking in the outback</strong>
					<span>My week in Australia</span>
				</a>
			</li>
		</ul>
		<div id="slider-arrows">
			<div class="slider-nav-left">
				<a class="previous" href="#"><img src="<?php bloginfo( 'template_url' ); ?>/images/feature-sld-nav-left.png" alt="Scroll left" width="32" height="27"/></a>
			</div>
			<div class="slider-nav-right">
				<a class="next" href="#"><img src="<?php bloginfo( 'template_url' ); ?>/images/feature-sld-nav-right.png" alt="Scroll right" width="32" height="27"/></a>
			</div>
		</div><!--end slider-arrows-->
	</div><!--end feature-sidebar-->
</div><!--end feature-->
<div class="feature-bottom clear"></div>